services:
  backend:
    build: .
    container_name: miguel-api
    restart: always
    expose:
      - "3000"
    environment:
      PORT: 3000
      JWT_SECRET: "019283"
      ADMIN_USER: "miguelalves"
      ADMIN_PASS: "barbershopma"
    volumes:
      - dados_miguel:/app/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miguel-api.rule=Host(`api-miguel.unvgroup.tech`)"
      - "traefik.http.routers.miguel-api.entrypoints=websecure"
      - "traefik.http.routers.miguel-api.tls.certresolver=myresolver"
      - "traefik.http.services.miguel-api.loadbalancer.server.port=3000"

volumes:
  dados_miguel:
