services:
  backend:
    build: .
    container_name: miguel-api
    restart: always
    ports:
      - "3002:3002"
    environment:
      PORT: 3002 # Força o Node.js a rodar na 3002
      JWT_SECRET: "019283"
      ADMIN_USER: "miguelalves"
      ADMIN_PASS: "barbershopma"
    volumes:
      - dados_miguel:/app/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miguel.rule=Host(`api-miguel.unvgroup.tech`)"
      - "traefik.http.routers.miguel.entrypoints=websecure"
      - "traefik.http.routers.miguel.tls.certresolver=myresolver"
      # 👇 ESTA É A LINHA QUE RESOLVE O SEU PROBLEMA:
      - "traefik.http.services.miguel.loadbalancer.server.port=3002"

volumes:
  dados_miguel:
